const PRODUCT_TEXT_REPLACEMENTS: Array<[RegExp, string]> = [
  [/Settings now reads live shell\/runtime posture first, while keeping typed fallback for anything the probes cannot safely read\./gi, "设置页会优先读取实时 shell 与运行态姿态；探针无法安全读取的项目仍保留类型化回退。"],
  [/Startup routing now mirrors the local preflight chain inside Settings: build ready, Electron ready, display not-required, and start ready\./gi, "启动路由已在设置页同步本地预检链：构建就绪、Electron 就绪、无需显示环境、启动就绪。"],
  [/Smoke remains the offline validation path while the runtime progressively adds live local probes\./gi, "Smoke 仍作为离线验证路径，运行态会逐步补充本地实时探针。"],
  [/Capability provenance across local skill roots, extension bundles, plugin caches, and MCP roots\./gi, "统一展示本地技能根、扩展包、插件缓存和 MCP 根路径的能力来源。"],
  [/OpenClaw plugin load paths and curated cache fallback will populate here from local runtime data\./gi, "OpenClaw 插件加载路径和精选缓存回退会从本地运行态数据填入这里。"],
  [/Extension-bundled skills remain explicitly tracked as a separate provenance source\./gi, "扩展内置技能会作为独立来源继续追踪。"],
  [/Codex plugin cache present .*? and kept connector rows on Studio-local execution plus blocked host\/runtime previews only\./gi, "已检测到 Codex 插件缓存；连接器行保持在 Studio 本地执行，只保留受保护的宿主与运行态预览。"],
  [/No dedicated MCP roots were detected locally, so the alpha shell keeps connector actions on structured fallback instead of inventing readiness\./gi, "本机未检测到专用 MCP 根路径，因此 alpha 壳层会把连接器动作保留在结构化回退状态，不伪造就绪。"],
  [/No dedicated MCP roots were found in the known .*? locations\./gi, "已知运行态位置中未发现专用 MCP 根路径。"],
  [/standard profile · exec ask\/always · search on \(brave\) · fetch on\./gi, "标准配置 · 执行前询问/始终允许 · Brave 搜索开启 · 抓取开启。"],
  [/exec ask\/always/gi, "执行前询问/始终允许"],
  [/Dashboard, Agents, Codex, Skills, and Tools\/MCP now mix local runtime observations with typed fallback where probes stay intentionally read-only\./gi, "总览、高级诊断、Codex、能力和工具/MCP 会混合本地运行态观测；探针保持只读时使用类型化回退。"],
  [/Renderer is receiving live-backed observations with typed fallback still available for missing probes\./gi, "渲染端正在接收实时观测；缺失探针仍可使用类型化回退。"],
  [/Renderer, bridge, and shared contracts live in the monorepo\./gi, "渲染端、桥接层和共享契约都在这个 monorepo 内。"],
  [/Current shell and repo context\./gi, "当前 shell 与仓库上下文。"],
  [/No interactive session is currently visible through the runtime probe\./gi, "当前运行态探针未发现可见的交互会话。"],
  [/Shell mode and integration posture\./gi, "壳层模式与集成姿态。"],
  [/Focus the right rail on boundary state and keep dock context visible\./gi, "把右侧栏聚焦到边界状态，并保留停靠区上下文。"],
  [/Move the shell into trace-first posture for the current focused slot\./gi, "把当前聚焦槽位切到优先追踪姿态。"],
  [/Bias the shell toward the focused slot trace and preview posture\./gi, "让壳层优先展示当前槽位追踪和预检姿态。"],
  [/Bias the shell toward window intents, placeholders, and review posture\./gi, "让壳层优先展示窗口意图、占位状态和审查姿态。"],
  [/Focused slot, recommended action, validator posture, and follow-up path are surfaced together for the current flow\./gi, "当前流程会同时展示聚焦槽位、推荐动作、校验姿态和后续路径。"],
  [/Tracking approval and future-executor requirements for withheld host-side actions\./gi, "追踪受保护宿主动作所需的审批与未来执行器条件。"],
  [/Extending the route shell and page registry\./gi, "扩展路由壳层与页面注册表。"],
  [/Route expansion stayed within the shared contract boundary\./gi, "路由扩展仍保持在共享契约边界内。"],
  [/System status and sessions are the first safe real integrations\./gi, "系统状态与会话是第一批安全接入的真实集成。"],
  [/Fallback delegation topology keeps spawn path, isolation posture, background lanes, and handoff state visible without launching any real subagents or host-side workers\./gi, "回退协作拓扑会显示启动路径、隔离姿态、后台通道和交接状态，但不会启动真实子代理或宿主侧工作器。"],
  [/Gateway target/gi, "网关目标"],
  [/Gateway 已连接/gi, "网关已连接"],
  [/Network 受限/gi, "网络受限"],
  [/This operation was aborted/gi, "操作已中止"],
  [/Loaded:/gi, "已加载："],
  [/enabled;/gi, "已启用；"],
  [/preset:/gi, "预设："],
  [/provider:/gi, "提供方："],
  [/connected/gi, "已连接"],
  [/latest batch/gi, "最新批次"],
  [/runtime sampled/gi, "运行态已采样"],
  [/runtime connected/gi, "运行态已连接"],
  [/runtime 调用成功/gi, "运行态调用成功"],
  [/runtime 批次/gi, "运行态批次"],
  [/metric 未采样/gi, "指标未采样"],
  [/Gateway runtime service/gi, "网关运行服务"],
  [/runtime service/gi, "运行服务"],
  [/runtime metric/gi, "运行指标"],
  [/rolling buffer/gi, "滚动缓存"],
  [/Shell snapshot/gi, "Shell 快照"],
  [/Runtime metric/gi, "运行指标"],
  [/Gateway\/Hermes/gi, "网关/Hermes"],
  [/Rolling buffer/gi, "滚动缓存"],
  [/5s refresh/gi, "5 秒刷新"],
  [/samples/gi, "个样本"],
  [/sample/gi, "样本"],
  [/snapshot \/ service/gi, "快照 / 服务"],
  [/shell snapshot\/fallback/gi, "shell 快照/回退"],
  [/Claude snapshot/gi, "Claude 快照"],
  [/Studio Alpha bootstrap/gi, "Studio Alpha 初始化"],
  [/Recent sessions/gi, "最近会话"],
  [/Codex tasks/gi, "Codex 任务"],
  [/monorepo/gi, "单体仓库"],
  [/Offline smoke/gi, "离线验证"],
  [/\bOperational\b/gi, "运行正常"],
  [/Studio-local root selection history plus blocked host\/runtime connect previews/gi, "Studio 本地根选择历史，以及受保护的宿主/运行态连接预览"],
  [/blocked host\/runtime connect previews only/gi, "仅保留受保护的宿主/运行态连接预览"],
  [/\b(\d+) install, (\d+) entry, (\d+) allow rule\. Installs:/gi, "$1 个安装，$2 个入口，$3 条允许规则。安装项："],
  [/\bEntries:/gi, "入口："],
  [/Load paths:/gi, "加载路径："],
  [/\bPlugin\b/gi, "插件"],
  [/\bmock\b/gi, "模拟"],
  [/updated navigation/gi, "更新了导航"],
  [/queued live probes/gi, "已排队实时探针"],
  [/\bNow\b/gi, "现在"],
  [/\bNext\b/gi, "下一步"],
  [/Just now/gi, "刚刚"],
  [/(\d+)\s+min ago/gi, "$1 分钟前"],
  [/(\d+)\s+hr ago/gi, "$1 小时前"],
  [/Open command palette/gi, "打开命令面板"],
  [/Close command palette/gi, "关闭命令面板"],
  [/Advance contextual flow/gi, "推进当前上下文流程"],
  [/Route to Dashboard/gi, "前往总览"],
  [/Activate Operator Shell View/gi, "进入操作壳层视图"],
  [/Activate Trace Deck View/gi, "进入轨迹台视图"],
  [/Activate Review Deck View/gi, "进入审查台视图"],
  [/Inspect Boundary Contract/gi, "检查边界契约"],
  [/Show Focused Slot Trace/gi, "查看聚焦槽位追踪"],
  [/Focus Lane Apply Slot/gi, "聚焦应用槽位"],
  [/Lane apply IPC slot/gi, "通道应用 IPC 槽位"],
  [/Execution Readiness Snapshot/gi, "执行就绪快照"],
  [/focused slot handoff/gi, "聚焦槽位交接"],
  [/delivery anchor/gi, "交付锚点"],
  [/review closeout/gi, "审查收口"],
  [/resume anchor/gi, "恢复锚点"],
  [/Operator Shell/gi, "操作壳层"],
  [/Trace Deck/gi, "轨迹台"],
  [/Review Deck/gi, "审查台"],
  [/Boundary Contract/gi, "边界契约"],
  [/Focused Slot Trace/gi, "聚焦槽位追踪"],
  [/Focus Lane Apply Slot/gi, "聚焦应用槽位"],
  [/Active Approval Queue/gi, "当前审批队列"],
  [/Host Executor/gi, "宿主执行器"],
  [/Shell Integrator/gi, "Shell 集成器"],
  [/Bridge Watcher/gi, "桥接观察器"],
  [/Active Agents/gi, "活动代理"],
  [/Waiting Lanes/gi, "等待通道"],
  [/Renderer shell owner/gi, "渲染壳层负责人"],
  [/Connector-adjacent runtime/gi, "连接器相邻运行态"],
  [/Runtime connector lane/gi, "运行态连接器通道"],
  [/OpenClaw tool profile/gi, "OpenClaw 工具配置"],
  [/OpenClaw plugin runtime/gi, "OpenClaw 插件运行态"],
  [/Codex local runtime/gi, "Codex 本地运行态"],
  [/Workspace root/gi, "工作区根目录"],
  [/Alpha version/gi, "Alpha 版本"],
  [/Recent workspace/gi, "最近工作区"],
  [/Bridge mode/gi, "桥接模式"],
  [/Fallback policy/gi, "回退策略"],
  [/Local gateway/gi, "本地网关"],
  [/Network probe/gi, "网络探针"],
  [/OpenClaw Config/gi, "OpenClaw 配置"],
  [/OpenClaw Plugins/gi, "OpenClaw 插件"],
  [/Plugin bridge/gi, "插件桥接"],
  [/MCP · mock/gi, "MCP · 模拟"],
  [/Validation/gi, "验证"],
  [/Runtime/gi, "运行态"],
  [/Workspace/gi, "工作区"],
  [/Configured/gi, "已配置"],
  [/Observed/gi, "已观测"],
  [/Fallback active/gi, "回退生效"],
  [/\bReady\b/gi, "就绪"],
  [/Unavailable/gi, "不可用"],
  [/Hybrid/gi, "混合"],
  [/\bActive\b/gi, "活动"],
  [/\bwaiting\b/gi, "等待中"],
  [/in-review/gi, "审查中"],
  [/local-only/gi, "仅本地"],
  [/preview-host/gi, "受保护预检"],
  [/withheld/gi, "受保护"],
  [/Phase\s*60/gi, "当前版本"],
  [/placeholder/gi, "占位状态"],
  [/dry-run/gi, "试运行"]
];

export function formatProductText(value: string | null | undefined, fallback = ""): string {
  if (!value) {
    return fallback;
  }

  return PRODUCT_TEXT_REPLACEMENTS.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}
